FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ffmpeg \
    tzdata \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    faster-whisper \
    flask \
    ctranslate2 \
    openai \
    python-dotenv \
    notion-client

WORKDIR /app
COPY summarize_text.py .
COPY .env .

EXPOSE 8000

CMD ["python3", "summarize_text.py"]
